site_name: EOSC Data Transfer Client
site_url: https://eosc-data-transfer-client-docs.web.cern.ch
site_description: EOSC Data Transfer Client Documentation
site_author: joao.pedro.batista.lopes@cern.ch
repo_name: GitLab
repo_url: https://gitlab.cern.ch/batistal/eosc-data-transfer-client

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
      - Client: reference/client.md
      - Endpoints: reference/endpoints.md
      - Models: reference/models.md
      - Exceptions: reference/exceptions.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]

markdown_extensions:
  - admonition
  - toc:
      permalink: true

